implemented extended gameLoop + added StartingPosition in pixel coord…
cephox/billiard pull request #8
Opened 2021-08-08 22:36 UTC by Jens988

…inate system

2021-08-08 22:36 UTC, Jens988 commented
schau mal drüber und merge dann

2021-08-09 07:30 UTC, cephox requested changes
Zu entfernen: Unbenutzte Imports

2021-08-09 07:30 UTC, cephox commented on src/de/jepa/billiard/object/balls/Ball.java
> +import javax.xml.stream.events.StartDocument;
Nicht verwendeter Import
=> für was?

2021-08-09 08:07 UTC, cephox approved these changes

2021-08-09 08:10 UTC, merged